apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: grpc-async
  labels:
    app.kubernetes.io/instance: grpc-server
    app.kubernetes.io/name: grpc-server-fibo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: grpc-server
      app.kubernetes.io/name: grpc-server-fibo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grpc-server
        app.kubernetes.io/name: grpc-server-fibo
    spec:
      containers:
        - name: grpc-server
          image: ghcr.io/gruppferi/grpc-service-comparison/grpc-server-async:0.1.0
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
            - containerPort: 8000
              name: metrics
              protocol: TCP

          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MODE
            value: "Normal"
          - name: WORKERS
            value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-svc
  namespace: grpc-async
spec:
  selector:
    app.kubernetes.io/instance: grpc-server
    app.kubernetes.io/name: grpc-server-fibo
  ports:
    - protocol: TCP
      port: 50051
      targetPort: grpc
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grpc-server
    app.kubernetes.io/name: grpc-server-fibo
  name: grpc-server-svc-metrics
  namespace: grpc-async
spec:
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: grpc-server
    app.kubernetes.io/name: grpc-server-fibo
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: grpc-server
    app.kubernetes.io/name: grpc-server-fibo
    release: prometheus-operator
  name: grpc-server
  namespace: grpc-async
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: grpc-server
      app.kubernetes.io/name: grpc-server-fibo
