# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/fibonacci.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/fibonacci.proto\x12\tfibonacci\" \n\x10IncrementRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"8\n\x11IncrementResponse\x12\x0e\n\x06number\x18\x01 \x01(\r\x12\x13\n\x0bserver_name\x18\x02 \x01(\t\"\x1d\n\x10\x46ibonacciRequest\x12\t\n\x01n\x18\x01 \x01(\r\"7\n\x11\x46ibonacciResponse\x12\r\n\x05value\x18\x01 \x01(\t\x12\x13\n\x0bserver_name\x18\x02 \x01(\t2\xa2\x01\n\x10\x46ibonacciService\x12\x46\n\tIncrement\x12\x1b.fibonacci.IncrementRequest\x1a\x1c.fibonacci.IncrementResponse\x12\x46\n\tFibonacci\x12\x1b.fibonacci.FibonacciRequest\x1a\x1c.fibonacci.FibonacciResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fibonacci_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INCREMENTREQUEST']._serialized_start=36
  _globals['_INCREMENTREQUEST']._serialized_end=68
  _globals['_INCREMENTRESPONSE']._serialized_start=70
  _globals['_INCREMENTRESPONSE']._serialized_end=126
  _globals['_FIBONACCIREQUEST']._serialized_start=128
  _globals['_FIBONACCIREQUEST']._serialized_end=157
  _globals['_FIBONACCIRESPONSE']._serialized_start=159
  _globals['_FIBONACCIRESPONSE']._serialized_end=214
  _globals['_FIBONACCISERVICE']._serialized_start=217
  _globals['_FIBONACCISERVICE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
