{
 "title": "grpc-test",
 "time": { "from": "2024-04-29T08:10:00.000Z", "to": "2024-04-29T08:45:59.000Z" },
 "panels": [
  {
   "title": "GRPC Normal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_requests_total{mode=\"Normal\"}) by (server_name, job, mode,pod)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "GRPC Normal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(grpc_requests_total{mode=\"Normal\"}[$__interval])) by (server_name, job, mode)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "GRPC Headless",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_requests_total{mode=\"Headless\"}) by (server_name, job, mode,pod)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "GRPC Headless",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(grpc_requests_total{mode=\"Headless\"}[$__interval])) by (server_name, job, mode,pod)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "GRPC Mesh",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_requests_total{mode=\"Mesh\"}) by (server_name, job, mode,pod)",
     "legendFormat": "{{server_name}}"
    }
   ]
  },
  {
   "title": "GRPC Mesh",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(increase(grpc_requests_total{mode=\"Mesh\"}[$__interval])) by (server_name, job, mode)",
     "legendFormat": "{{server_name}}"
    }
   ]
  }
 ]
}