# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from modules.proto import fibonacci_pb2 as proto_dot_fibonacci__pb2


class FibonacciServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Increment = channel.unary_unary(
                '/fibonacci.FibonacciService/Increment',
                request_serializer=proto_dot_fibonacci__pb2.IncrementRequest.SerializeToString,
                response_deserializer=proto_dot_fibonacci__pb2.IncrementResponse.FromString,
                )
        self.Fibonacci = channel.unary_unary(
                '/fibonacci.FibonacciService/Fibonacci',
                request_serializer=proto_dot_fibonacci__pb2.FibonacciRequest.SerializeToString,
                response_deserializer=proto_dot_fibonacci__pb2.FibonacciResponse.FromString,
                )


class FibonacciServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Increment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fibonacci(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FibonacciServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Increment': grpc.unary_unary_rpc_method_handler(
                    servicer.Increment,
                    request_deserializer=proto_dot_fibonacci__pb2.IncrementRequest.FromString,
                    response_serializer=proto_dot_fibonacci__pb2.IncrementResponse.SerializeToString,
            ),
            'Fibonacci': grpc.unary_unary_rpc_method_handler(
                    servicer.Fibonacci,
                    request_deserializer=proto_dot_fibonacci__pb2.FibonacciRequest.FromString,
                    response_serializer=proto_dot_fibonacci__pb2.FibonacciResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fibonacci.FibonacciService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FibonacciService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Increment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fibonacci.FibonacciService/Increment',
            proto_dot_fibonacci__pb2.IncrementRequest.SerializeToString,
            proto_dot_fibonacci__pb2.IncrementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fibonacci(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fibonacci.FibonacciService/Fibonacci',
            proto_dot_fibonacci__pb2.FibonacciRequest.SerializeToString,
            proto_dot_fibonacci__pb2.FibonacciResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
