apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-headless
  namespace: grpc
  labels:
    app.kubernetes.io/instance: grpc-server-headless
    app.kubernetes.io/name: grpc-server-headless-fibo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: grpc-server-headless
      app.kubernetes.io/name: grpc-server-headless-fibo
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: grpc-server-headless
        app.kubernetes.io/name: grpc-server-headless-fibo
    spec:
      containers:
        - name: grpc-server-headless
          image: ghcr.io/gruppferi/grpc-service-comparison/grpc-server:1.0.0
          ports:
            - containerPort: 50051
              name: grpc
              protocol: TCP
            - containerPort: 8000
              name: metrics
              protocol: TCP
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MODE
            value: "Headless"
          - name: WORKERS
            value: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-headless-svc
  namespace: grpc
spec:
  selector:
    app.kubernetes.io/instance: grpc-server-headless
    app.kubernetes.io/name: grpc-server-headless-fibo
  ports:
    - protocol: TCP
      port: 50051
      targetPort: grpc
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: grpc-server-headless
    app.kubernetes.io/name: grpc-server-headless-fibo
  name: grpc-server-headless-metrics
  namespace: grpc
spec:
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/instance: grpc-server-headless
    app.kubernetes.io/name: grpc-server-headless-fibo
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: grpc-server-headless
    app.kubernetes.io/name: grpc-server-headless-fibo
    release: prometheus-operator
  name: grpc-server-headless
  namespace: grpc
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/instance: grpc-server-headless
      app.kubernetes.io/name: grpc-server-headless-fibo
