name: Build, Push, and Update Kubernetes Manifests

on:
  push:
    branches:
      - main
      - ci-fix
      - develop
jobs:
  build-push-update:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Update image versions to') == false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use GitVersion
      id: gitversion
      uses: gittools/actions/gitversion/setup@v0.10.1
      with:
        versionSpec: 6.x

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}

    - name: Build and push grpc-client image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/grpc-client:${{ steps.gitversion.outputs.SemVer }} grpc-client/
        docker push ghcr.io/${{ github.repository }}/grpc-client:${{ steps.gitversion.outputs.SemVer }}

    - name: Build and push grpc-server image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/grpc-server:${{ steps.gitversion.outputs.SemVer }} grpc-server/
        docker push ghcr.io/${{ github.repository }}/grpc-server:${{ steps.gitversion.outputs.SemVer }}

    - name: Build and push grpc-client-async image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/grpc-client-async:${{ steps.gitversion.outputs.SemVer }} grpc-client-async/
        docker push ghcr.io/${{ github.repository }}/grpc-client-async:${{ steps.gitversion.outputs.SemVer }}

    - name: Build and push grpc-server-async image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/grpc-server-async:${{ steps.gitversion.outputs.SemVer }} grpc-server-async/
        docker push ghcr.io/${{ github.repository }}/grpc-server-async:${{ steps.gitversion.outputs.SemVer }}

    - name: Update Kubernetes manifests for grpc-client
      run: |
        sed -i "s|image: ghcr.io/${{ github.repository }}/grpc-client:.*|image: ghcr.io/${{ github.repository }}/grpc-client:${{ steps.gitversion.outputs.SemVer }}|g" grpc-client/kubernetes/*.yaml

    - name: Update Kubernetes manifests for grpc-server
      run: |
        sed -i "s|image: ghcr.io/${{ github.repository }}/grpc-server:.*|image: ghcr.io/${{ github.repository }}/grpc-server:${{ steps.gitversion.outputs.SemVer }}|g" grpc-server/kubernetes/*.yaml

    - name: Update Kubernetes manifests for grpc-client-async
      run: |
        sed -i "s|image: ghcr.io/${{ github.repository }}/grpc-client-async:.*|image: ghcr.io/${{ github.repository }}/grpc-client-async:${{ steps.gitversion.outputs.SemVer }}|g" grpc-client-async/kubernetes/*.yaml

    - name: Update Kubernetes manifests for grpc-server-async
      run: |
        sed -i "s|image: ghcr.io/${{ github.repository }}/grpc-server-async:.*|image: ghcr.io/${{ github.repository }}/grpc-server-async:${{ steps.gitversion.outputs.SemVer }}|g" grpc-server-async/kubernetes/*.yaml

    - name: Configure Git
      run: |
        git config --local user.name "${{ github.actor }}"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Commit and push changes
      run: |
        git add grpc-client/kubernetes/*.yaml grpc-server/kubernetes/*.yaml
        git add grpc-client-async/kubernetes/*.yaml grpc-server-async/kubernetes/*.yaml
        git commit -m "Update image versions to ${{ steps.gitversion.outputs.SemVer }} [workflow update]"
        git push origin main
